from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any


class PowerWorldAdapter(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def program_information(self) -> dict[str, Any]: ...
    @abstractmethod
    def open_case(self, path: str) -> None: ...
    @abstractmethod
    def close_case(self) -> None: ...
    @abstractmethod
    def run_script(self, command: str) -> str: ...
    @abstractmethod
    def get_field_list(self, object_type: str) -> list[dict[str, Any]]: ...
    @abstractmethod
    def get_rows(self, object_type: str, fields: list[str], filter_text: str = "") -> list[dict[str, Any]]: ...
    @abstractmethod
    def change_single(self, object_type: str, fields: list[str], values: list[Any]) -> None: ...
    @abstractmethod
    def save_state(self) -> None: ...
    @abstractmethod
    def load_state(self) -> None: ...
    @property
    @abstractmethod
    def solver_backed(self) -> bool: ...
